# KerogsPHP Framework Configuration
# https://github.com/KSInfinite/KerogsPHP-Framework
# Thanks for using it.

# SEO Configuration
seo:
  title: "KerogsPHP Framework"
  title_short: "KsPHP Framework"
  description: "KerogsPHP Framework. The framework for all your development needs."
  keywords: "KerogsPHP, PHP, Framework, website, html, css, easy, best, KerogsPHP Framework, kpf"
  author: "Kerogs"
  lang: "English"
  lang_short: "en"
  color: "#a038ec"
  image: "https://raw.githubusercontent.com/KSInfinite/KerogsPHP-Framework/main/.ksinf/banner.png"
  favicon: "src/img/logo.png"
  sitemap: "src/xml/sitemap.xml"

# Labs/test IP authorization Configuration
labs:
  enable: false
  labsIPAuth:
    - 127.0.0.1

# Other
other:
  use_database: false
  website_version: 1.0.0

framework:
  framework_version: 2.4.1-sh8
  title: "KerogsPHP Framework"
  title_short: "KsPHP Framework"